# +------------------+ #
#      AutoBackup      #
# +------------------+ #

# Information:
# - ${project.name} - ${project.description}
#   by ${author}
# - This config was first generated for plugin version ${project.version}
# - If you need to regenerate the default config, delete or rename this file
#   and restart the server.

# +------------- Start of Config -------------+

# Determines which kind of backup to perform on default, aka when the command /backup is run.
default-modes: ['overworld', 'nether', 'end']

# Determines whether to exclude the backup directory from a potential backup.
# It is HIGHLY RECOMMENDED that you leave this to the default setting (true)!
# Disabling this setting will dramatically increase both occupied disk space and backup taking time.
# Set to false at your own risk!
exclude-backup: true

# Determines where to save the backups. DO NOT CHANGE unless you are exporting the backups outside
# the Minecraft server root.
backup-dir: '/backups'

# Determines whether the paths in this config are to be taken relative to the Minecraft server root
# as opposed to actual system root. Leave the default option (true) unless you know what you
# are doing and you would like to export the backups outside your Minecraft server directory.
relative-paths: true

# Determines whether or not to log to console when backups are performed successfully (recommended).
# If a backup fails, the plugin will log it regardless of whether this option is set to true or false.
log-to-console: true

# Determines whether or not to perform the first iteration of a scheduled backup cycle on server start
# and on plugin reload, or wait the scheduled time interval before the first cycle.
# Setting to true may cause the server startup time to increase, depending on the other plugins on the server
# and the backup size.
immediate-backup: false

# Determines whether the console is allowed to perform a backup even if manual trigger for the backup
# (allow-manual option) is disabled.
allow-force-console: true

# Use this configuration section to determine what is backed up.
# Every list entry is a different backup mode. Feel free to add your own modes and remove the examples
# you don't need.
# - The mode name (example: everything, plugin-jars, etc) can be chosen freely. Avoid using 'default' though.
# - The dir option determines what folder is backed up. '/' means server root.
# - The allow-manual option determines whether this backup can be performed by the /backup command
# - The schedule option determines whether or not to perform the backup manually every x minutes.
#   If set to 0 or negative, the scheduled backup is disabled.
#   If set to a positive integer, the value indicates the time in minutes between every automatic backup.
# NOTE: These are just examples! You should add and tweak the ones you need and get rid of those you
# do not need. In particular, the backup 'everything' is extremely inefficient and can take very long times. It
# is therefore highly discouraged. You should rather setup separate smaller backups, ie. one for plugin data, one for
# each world, etc.
backup-modes:
  - name: 'everything'
    dir: '/'
    allow-manual: true
    schedule: 0
  - name: 'plugins'
    dir: '/plugins'
    allow-manual: false
    schedule: 0
  - name: 'overworld'
    dir: '/world'
    allow-manual: true
    schedule: 720
  - name: 'nether'
    dir: '/world_nether'
    allow-manual: true
    schedule: 1440
  - name: 'end'
    dir: '/world_the_end'
    allow-manual: true
    schedule: 2880

# +-------------- End of Config --------------+
# You are done configuring AutoBackup. Enjoy :)